#!/usr/bin/env bash
#This script transfers a file from our client to a server 
#using scp (secure file copy) 

#Requirements:
#Accepts 4 parameters
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses

if [ "$#" -le 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp  "$1"-o StrictHostKeyChecking=No "$2" "$3@$4":~/
fi
