#!/usr/bin/env bash
#This script installs nginx on remote web server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start

