#!/usr/bin/env bash
#This script installs nginx on remote web server
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "17i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo /etc/init.d/nginx start

