#!/usr/bin/env bash
#This script automates the debugging of this issue: Ubuntu container’s Nginx installation is not listening on port 80
#Requirements:Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
