#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS.

FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
    echo "The user $username is part of the $groupdid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $username"  
done < $FILENAME