#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for 9th iteration display Hi

i=1
while [ $i -le 11 ]
do

if (( i == 10))
	then 
	
		echo "Hi"
	else
		echo "Best School"
fi
	((i++))
done
