#!/usr/bin/env bash
#This script fixed the docker container 
#by getting Apache to run on the container 
#and to return a page containing Hello Holberton when querying the root of it.
sudo service apache2 restart