#!/usr/bin/env bash
# This is a shorter script configures the container so that Nginx is running as the nginx user.
chmod 644 /etc/nginx/nginx.conf
chown nginx /etc/nginx/nginx.conf
sed -i -e 's#listen 80#listen 8080#' -e 's#listen \[::\]:80#listen \[::\]:8080#' /etc/nginx/sites-available/default
pkill -9 apache
sudo -u nginx service nginx restart
